import {
  IoIosLogOut,
  IoIosSpeedometer,
  IoIosPeople,
  IoIosToday,
  IoIosStar,
  IoIosStarHalf,
  IoIosStarOutline,
} from "react-icons/io";
import {
  MdArrowDropDown,
  MdArrowLeft,
  MdDelete,
  MdEditSquare,
  MdOutlineClear,
  MdSystemUpdateAlt,
  MdClose,
  MdReceiptLong,
  MdAppRegistration,
  MdOutlineTrendingUp,
  MdPerson,
  MdRemoveRedEye,
  MdDashboardCustomize,
} from "react-icons/md";
const icons = {
  IoIosLogOut,
  IoIosSpeedometer,
  IoIosPeople,
  IoIosToday,
  MdArrowDropDown,
  MdArrowLeft,
  MdDelete,
  MdEditSquare,
  MdOutlineClear,
  MdSystemUpdateAlt,
  MdClose,
  MdReceiptLong,
  MdAppRegistration,
  MdOutlineTrendingUp,
  MdPerson,
  MdRemoveRedEye,
  IoIosStar,
  IoIosStarHalf,
  IoIosStarOutline,
  MdDashboardCustomize,
};
export default icons;
